language: node_js
node_js:
  "8"
script: npm run generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
  repo: cursorclub/cursorclub.github.io
  fqdn: cursor.club
  target_branch: master
