language: node_js
node_js:
  "node"
script: npm run generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
  repo: cursorclub/cursorclub.github.io
  target_branch: master
cache:
  directories:
    - "node_modules"
